[package]
name = "cpi-caller"
version = "0.0.1"
description = "Test Program for SPL-Token 2022 CpiGuard"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.14.4"
spl-token-2022 = { version = "0.4", path="../../program-2022", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
